# site settings
title: FTA
subtitle: Fundacion Turismo de Altura
email: fundacionturismodealtura@gmail.com
description: Somo una organización no gubernamental sin fines de lucro
baseurl: "./" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Catia La Mar
state: LA
zip_code: 1160
country: Venezuela
phone: +58 (555) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Instagram: https://www.instagram.com/laymontarratia/
  Facebook: https://www.facebook.com/laymontarratia

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
